import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MyThemeContextProvider } from "./context/themeContext";
import { PageTransitionProvider } from "./context/PageTransitionContext";
import AnimateLayout from "./components/General/AnimateLayout";
import Navbar from "./components/navbar";
import { UserProvider } from "./context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MyThemeContextProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <UserProvider>
            <Navbar />
            <PageTransitionProvider>
              <AnimateLayout>{children}</AnimateLayout>
            </PageTransitionProvider>
          </UserProvider>
        </body>
      </MyThemeContextProvider>
    </html>
  );
}
